name: Orderium
version: ${version}
main: me.karven.orderium.load.Orderium
bootstrapper: me.karven.orderium.load.Bootstrapper
api-version: '1.21'
folia-supported: false
authors: [ Karven ]
description: An order plugin
permissions:
  orderium.admin:
    default: op

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true